---

- name: establish dependencies
  package:
    name: ca-certificates
    state: present
  tags: install

- name: enable dynamic ca configuration on rhel6
  shell: /bin/update-ca-trust enable
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 6
  tags: configure

- name: import os family variables
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: configure

- name: copy certificate authority to trusted CA path
  copy:
    src: "{{ item }}"
    dest: "{{ ca_path }}/"
    owner: root
    group: root
    mode: "u=rw,go=r" 
  with_fileglob:
    - "{{ certificates_path }}/*"
  notify:
    - update trusted ca {{ ansible_os_family | lower }}
  tags: configure
