---

- name: establish dependencies
  package:
    name: ca-certificates
    state: present
  tags: install

- name: enable dynamic ca configuration on rhel6
  command: /bin/update-ca-trust enable
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 6
  tags: install, configure

- name: import os family variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: configure

- name: copy certificate authority to trusted CA path
  copy:
    src: "{{ item }}"
    dest: "{{ ca_path }}/"
    owner: root
    group: root
    mode: "u=rw,go=r"
  loop: "{{ ca_trusted_certificates }}"
  register: certificates
  tags: configure

- name: update trusted CA   # noqa 503
  when:
    - certificates.changed
    - ansible_os_family in ["Debian", "RedHat"]
  become: true
  command: "{{ update_trusted_system_ca }}"
  tags: configure
