---

- name: establish dependencies
  package:
    name: ca-certificates
    state: present
  tags: install

- name: enable dynamic ca configuration on rhel6
  command: /bin/update-ca-trust enable
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 6
  tags: install

- name: import os family variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: configure

- name: copy certificate authority to trusted CA path
  copy:
    src: "{{ item }}"
    dest: "{{ ca_path }}/"
    owner: root
    group: root
    mode: "u=rw,go=r"
  loop: "{{ query('fileglob', '%s/*' | format(certificates_dir)) }}"
  register: certificates
  tags: configure

- name: Debian  | update trusted CA   # noqa 503
  when:
    - certificates.changed
    - ansible_os_family == "Debian"
  become: true
  command: /usr/sbin/update-ca-certificates

- name: RedHat | update trusted CA    # noqa 503
  when:
    - certificates.changed
    - ansible_os_family == "RedHat"
  become: true
  command: /bin/update-ca-trust
